### ISSUE TITLE
Won't work for me

### ISSUE THREAD

**Issue by lolmaus** [MaazAli/ember-cli-sortable#1]
Hi!

I'm trying to make use of `ember-cli-sortable`. I do see a list of items, but no styles are applied to the list and i'm unable to sort it: when i try dragging an item with the mouse,  text is selected instead.

Any suggestions?

**Comment by lolmaus** [comment]
No errors in console.

**Comment by MaazAli** [comment]
Did you specify the `handle` property?

**Comment by MaazAli** [comment]
@lolmaus i'm going to close this issue, but we can continue chatting if you're still running into issues.

**Comment by lolmaus** [comment]
Hey, @MaazAli, i just followed the readme.

I ended up using vanilla Rubaxa Sortable rather then `ember-cli-sortable`, but if you want i can try reproducing the problem again.

**Comment by MaazAli** [comment]
Could I see the code that you had or did it match the code provided in the readme? @lolmaus

**Comment by lolmaus** [comment]
I took trouble to create a demo repo: https://github.com/lolmaus/ember-cli-sortable-test

It's a blank `ember new` project where i followed the steps of the `ember-cli-sortable` readme.

`Sortable` is available on `window`, no errors in console.

**Comment by MaazAli** [comment]
@lolmaus, draggable should be `.item` and not `.item--sortable`. I'll fix that in the readme. I've tested your demo repo with .item as the draggable value and it works fine.
