### ISSUE TITLE
ember-cli-sortable is not working with Ember 1.13.2

### ISSUE THREAD

**Issue by Cryrivers** [MaazAli/ember-cli-sortable#4]
Get error message when try dragging and dropping. 

The message is `Uncaught Error: Assertion Failed: You must use Ember.set() to set the`0`property (of aaa,bbb) to`bbb`.`

**Comment by MaazAli** [comment]
Follow this pull request: https://github.com/MaazAli/ember-cli-sortable/pull/5

**Comment by drapergeek** [comment]
I'm still seeing issues after the upgrade to 1.13. The item disappears after sorting. I'm trying to dig through the code now and see what's going on.

**Comment by laantorchaweb** [comment]
same issue here I'm using ember-cli 1.13.8, the items disappear after moving it.

**Comment by yanzixiang** [comment]
same issue here I'm using ember-cli 1.13.9, the items disappear after moving it.

``` javascript
 // Remove the duplicate
 //evt.item.parentNode.removeChild(evt.item);
```

**Comment by MaazAli** [comment]
https://github.com/MaazAli/ember-cli-sortable/pull/8, does that pull request help?

**Comment by laantorchaweb** [comment]
@MaazAli yes it does, I just made a test project and changed the addon file to match the PR and it's working fine with those changes.

**Comment by MaazAli** [comment]
It's been merged in.

**Comment by laantorchaweb** [comment]
awesome, can we pull it from npm or directly trough github for now?

**Comment by MaazAli** [comment]
Through github, I need to update npm still.

**Comment by laantorchaweb** [comment]
@MaazAli from my tests everything is working fine now, do you have an ETA on when you're going to publish the current version to NPM? is there anything left to tackle before publishing it? Let me know if I can help, thanks!

**Comment by MaazAli** [comment]
It's updated on npm now.
